'use client';
import styled from 'styled-components';
import { NavProvider } from './contexts/NavContext';
// import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Purhcase Platform',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <NavProvider>
      <html lang="en">
        <Body>
          <main>{children}</main>
        </Body>
      </html>
    </NavProvider>
  );
}

const HTML = styled.html`
  width: 100vw;
`;

const Body = styled.body`
  margin: 0;
  width: 100vw;
`;
